### ISSUE TITLE
млн

### ISSUE THREAD

**Issue by Fly4545** [hsdn/tera-guide#2]
на ласте в млн вылетает из игры .
F:\ЗАГРУЗКИ\tera-proxy-beta\tera-proxy-beta\mods\tera-guide-master\lib.js:138
                } else if (entity.loc !== undefined) {
                                       ^ 

TypeError: Cannot read property 'loc' of undefined
    at Timeout._onTimeout (F:\ЗАГРУЗКИ\tera-proxy-beta\tera-proxy-beta\mods\tera-guide-master\lib.js:138:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by hsdn** [comment]
Исправлено. Спасибо за обращение.
