### ISSUE TITLE
Something broke with the previous update 

### ISSUE THREAD

**Issue by salman90299** [hsdn/tera-guide#23]
{"type": "func","func": SpawnCircle.bind(null,false,445,0,0,14,160,0,3000)},
		^

SyntaxError: Unexpected token '{'
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at Object.runInThisContext (vm.js:306:10)
    at Module._compile (internal/modules/cjs/loader.js:883:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by shindmitry** [comment]
Fixed https://github.com/hsdn/tera-guide/commit/b2c7a2e7004ab0d2dfd7346a6eb37575a1f9326e.
