### ISSUE TITLE
alrdy put tera guide but not work

### ISSUE THREAD

**Issue by Zazuno** [hsdn/tera-guide#41]
[18:26:32.097] [toolbox] Starting the network proxy...
[18:26:32.104] [update] Auto-update started!
[18:26:33.027] [update] WARNING: Auto-update disabled for module CaaliLogger!
[18:26:36.857] [update] Auto-update complete!
[18:26:36.868] [mods] ERROR: Module "PSP" (skill-prediction) cannot be loaded while "ping-remover" is installed!
[18:26:36.869] [mods] Preloaded module "Command" (command)
[18:26:36.871] [mods] Preloaded module "tera-game-state"
[18:26:36.872] [mods] Preloaded module "auto-vanguard"
[18:26:36.873] [mods] Preloaded module "badGUI" (badGui)
[18:26:36.873] [mods] Preloaded module "badGUILoader" (badGUILoader)
[18:26:36.874] [mods] Preloaded module "Bugfix" (bugfix)
[18:26:36.875] [mods] Preloaded module "ExoMarker" (ExoMarker)
[18:26:36.877] [mods] Preloaded module "FPS-UTILS" (fps-utils)
[18:26:36.878] [mods] Preloaded module "<font color='#FDD017'>Box</font>" (generic-box-opener-item-user)
[18:26:36.882] [mods] Preloaded module "InstantEverything" (instant-everything)
[18:26:36.883] [mods] Preloaded module "Lazy Steroids" (Lazy Steroids)
[18:26:36.884] [mods] Preloaded module "library"
[18:26:36.898] [mods] Preloaded module "TeraNotifier" (notifier)
[18:26:36.899] [mods] Preloaded module "ping"
[18:26:36.901] [mods] Preloaded module "ping-remover"
[18:26:36.903] [mods] Preloaded module "Camera Control" (camera-control)
[18:26:36.904] [mods] Preloaded module "Guide Core" (tera-guide-core)
[18:26:36.905] [mods] Preloaded module "Guide" (tera-guide)
[18:26:36.905] [mods] Preloaded module "TERA-Message" (tera-message)
[18:26:36.926] [toolbox] Ready, waiting for game client start!
[18:26:37.524] [toolbox] Client reconnected (GF v98.2)
[18:26:37.525] [mods] Connected module "tera-game-state" to client
[18:26:37.526] [mods] ERROR: Module "badGUILoader" (badGUILoader) could not be connected to client!
[18:26:37.526] [mods] ERROR: Please contact the module's author: https://discord.gg/uhDAXWQ
[18:26:37.527] Error: Incompatible with 64-bit client. Wait for the module to be updated!
    at new <anonymous> (C:\TERA SEA\baru\TeraToolbox\bin\mod-legacy-wrapper.js:17:23)
    at Mod.loadClientInstance (C:\TERA SEA\baru\TeraToolbox\bin\mod.js:542:31)
    at ModManager.loadClient (C:\TERA SEA\baru\TeraToolbox\bin\mod-manager.js:215:20)
    at C:\TERA SEA\baru\TeraToolbox\bin\mod-manager.js:188:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllClient (C:\TERA SEA\baru\TeraToolbox\bin\mod-manager.js:186:25)
    at TeraClientInterfaceConnection.<anonymous> (C:\TERA SEA\baru\TeraToolbox\bin\proxy.js:160:41)
    at TeraClientInterfaceConnection.emit (events.js:223:5)
    at Socket.<anonymous> (C:\TERA SEA\baru\TeraToolbox\node_modules\tera-client-interface\index.js:46:38)
    at Socket.emit (events.js:223:5)
[18:26:37.530] [toolbox] Loaded protocol version 373824 (GF v98.2).
[18:26:53.486] [toolbox] Redirecting (Asia) - Shen (GF-39) from 127.0.0.20:9250 to 104.215.148.89:7802
[18:26:53.487] [toolbox] Redirecting (DE) - Yurian (GF-28) from 127.0.0.20:9251 to 79.110.94.213:7803
[18:26:53.488] [toolbox] Redirecting (RU) - Shakan (GF-40) from 127.0.0.20:9252 to 79.110.94.212:7805
[18:26:53.488] [toolbox] Redirecting (FR) - Seren (GF-29) from 127.0.0.20:9253 to 79.110.94.214:7804
[18:26:53.489] [toolbox] Redirecting (INT) - Mystel (GF-38) from 127.0.0.20:9254 to 79.110.94.211:7801
[18:26:54.877] [connection] routing 127.0.0.1:56394 to 104.215.148.89:7802
[18:26:54.880] [mods] Applied module "Command" (command) to server connection
[18:26:54.880] [mods] Applied module "auto-vanguard" to server connection
[18:26:54.881] [mods] Applied module "badGUI" (badGui) to server connection
[18:26:54.882] [mods] Applied module "Bugfix" (bugfix) to server connection
[18:26:54.883] [mods] Applied module "ExoMarker" (ExoMarker) to server connection
[18:26:54.890] [mods] Applied module "FPS-UTILS" (fps-utils) to server connection
[18:26:54.891] [mods] Applied module "<font color='#FDD017'>Box</font>" (generic-box-opener-item-user) to server connection
[18:26:54.892] [mods] Applied module "InstantEverything" (instant-everything) to server connection
[18:26:54.892] [mods] Applied module "Lazy Steroids" (Lazy Steroids) to server connection
[18:26:54.898] [mods] Applied module "library" to server connection
[18:26:54.899] [mods] Applied module "TeraNotifier" (notifier) to server connection
[18:26:54.899] [mods] Applied module "ping" to server connection
[18:26:54.942] [mods] Applied module "ping-remover" to server connection
[18:26:54.944] [mods] Applied module "Camera Control" (camera-control) to server connection
[18:26:54.954] [mods] Applied module "Guide Core" (tera-guide-core) to server connection
[18:26:54.955] [tera-guide] ERROR: Warning!
Depended module "tera-guide-core" needed for TERA-Guide is not installed!
Please download and install: https://github.com/hsdn/tera-guide-core

[18:26:54.955] [mods] ERROR: Module "Guide" (tera-guide) could not be applied to server connection!
[18:26:54.956] [mods] ERROR: Please contact the module's author: https://github.com/hsdn/tera-guide/issues
[18:26:54.956] TypeError: mod.require.tera-guide-core.load is not a function
    at new exports.NetworkMod (C:\TERA SEA\baru\TeraToolbox\mods\tera-guide-master\index.js:5:34)
    at Mod.loadNetworkInstance (C:\TERA SEA\baru\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\TERA SEA\baru\TeraToolbox\bin\mod-manager.js:252:20)
    at C:\TERA SEA\baru\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (C:\TERA SEA\baru\TeraToolbox\bin\mod-manager.js:231:25)
    at Socket.<anonymous> (C:\TERA SEA\baru\TeraToolbox\bin\connection-manager.js:59:33)
    at Socket.emit (events.js:228:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1120:10)
[18:26:54.957] [mods] Applied module "TERA-Message" (tera-message) to server connection

**Comment by PsykoDev** [comment]
https://github.com/hsdn/tera-guide/tree/7096d1f369e5230c14eb839b59d5513fbee35d2a use this version and disable auto update for now

**Comment by fisherman1717** [comment]
what did this guide author try to do that broke his own mod lol

**Comment by shindmitry** [comment]
Please check https://github.com/hsdn/tera-guide/issues/43
