### ISSUE TITLE
error running hook for S_BOSS_GAGE_INFO<3>

### ISSUE THREAD

**Issue by Loliconera** [hsdn/tera-guide#44]
in the Bahaar guide I got the following error and some objects did not generate

```
[11:07:27.221] [dispatch] [tera-guía] handle: error running hook for S_BOSS_GAGE_INFO<3>
hook: (anonymous) in tera-guía
data: {
  id: 3519399282366773n,
  huntingZoneId: 444,
  templateId: 2000,
  target: 0n,
  unk1: 0,
  unk2: 0,
  curHp: 30089331250n,
  maxHp: 30089331250n,
  unk3: 1
}
error: mod is not defined
    at Handlers.start_events (C:\Users\------------\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\handlers.js:421:5)
    at Guide.handleEvent (C:\Users\--------------\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\guide.js:243:18)
    at Object.callback (C:\Users\---------------\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\events.js:120:9)
[11:08:49.669] [dispatch] [tera-guía] handle: error running hook for S_BOSS_GAGE_INFO<3>
hook: (anonymous) in tera-guía
data: {
  id: 3519399282366773n,
  huntingZoneId: 444,
  templateId: 2000,
  target: 0n,
  unk1: 0,
  unk2: 0,
  curHp: 30089331250n,
  maxHp: 30089331250n,
  unk3: 1
}
error: mod is not defined
    at Handlers.start_events (C:\Users\-------------------\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\handlers.js:421:5)
    at Guide.handleEvent (C:\Users\----------------\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\guide.js:243:18)
    at Object.callback (C:\Users\------------------\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\events.js:120:9)
```

**Comment by Loliconera** [comment]
this error was present 5 min ago

**Comment by shindmitry** [comment]
Hi, it's fixed on https://github.com/hsdn/tera-guide-core/commit/712a2a21536eb53087d543563b50196c0b158355

**Comment by Loliconera** [comment]
[11:32:26.311] [update] ERROR: Imposible actualizar automáticamente el módulo tera-guide-core:
[11:32:26.311] Failed to update the following module files:
 - lib/core/handlers.js
 - ERROR: https://raw.githubusercontent.com/hsdn/tera-guide-core/master/lib/core/handlers.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
   + NoPing (if you're using it) has a bug that can fuck up the download
[11:32:26.313] [update] Por favor dirígete a https://github.com/hsdn/tera-guide/issues y sigue las instrucciones o solicita ayuda.
[11:32:26.313] [update] Alternativamente, pregunta aqui: https://discord.gg/659YbNY
[11:32:26.440] [update] ATENCIÓN: La actualización automática se ha desactivado para el módulo translate-chat!
[11:32:26.612] [update] Actualizacion automatica completada!
[11:32:26.613] [update] ERROR: El módulo tera-guide-core no pudo ser actualizado y puede estar roto!

**Comment by shindmitry** [comment]
It's a github cache problem. You need to wait and try start update process again.

**Comment by Loliconera** [comment]
it is fixed

**Comment by Loliconera** [comment]
[11:45:16.458] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:23.906] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:23.907] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:23.907] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:25.717] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:25.718] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:27.452] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:44.905] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:48.907] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:48.908] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:48.908] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:50.736] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:50.738] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:52.454] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:59.905] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:59.906] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:59.906] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:45:59.907] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:06.092] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:18.905] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:18.907] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:18.907] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:20.734] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:20.735] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:22.453] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:29.202] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:36.905] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:36.908] [tera-guía] ERROR: An event has invalid type: spawn_func
[11:46:36.909] [tera-guía] ERROR: An event has invalid type: spawn_func

**Comment by shindmitry** [comment]
Fixed on this https://github.com/hsdn/tera-guide-core/commit/6de19680690577786a74b16933e2855e9e42666e

**Comment by Loliconera** [comment]
lol xd
