### ISSUE TITLE
Fresh toolbox install. both tera-guide and tera-guide-core are in

### ISSUE THREAD

**Issue by erika2145154** [hsdn/tera-guide#45]
Require stack:
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\proxy.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\index-gui.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7012:16)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Mod.loadCache (C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod.js:440:35)
    at ModManager.load (C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:128:22)
    at C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:102:22
    at Map.forEach (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\mod.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\mod-manager.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\proxy.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\loader-gui.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\index-gui.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
    undefined
  ]
}
[21:02:07.843] [mods] ERROR: Module "tera-guide-core-master" could not be preloaded!
[21:02:07.844] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[21:02:07.844] Error: Cannot find module 'C:\Users\erika\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core-master'
Require stack:
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\proxy.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\index-gui.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7012:16)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Mod.loadCache (C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod.js:440:35)
    at ModManager.load (C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:128:22)
    at C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:102:22
    at Map.forEach (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\mod.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\mod-manager.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\proxy.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\loader-gui.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\index-gui.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
    undefined
  ]
}

**Comment by shindmitry** [comment]
Hi,
Rename **tera-guide-core-master** to **tera-guide-core**, or just delete this folder. 
Its installed automatically after run the TeraToolbox.

**Comment by erika2145154** [comment]
> 
> 
> Hi,
> Rename **tera-guide-core-master** to **tera-guide-core**, or just delete this folder.
> Its installed automatically after run the TeraToolbox.

I did this but the same error message pops up :(

**Comment by shindmitry** [comment]
Your error says a folder "tera-guide-core-master" it is not the correct path to load. Just remove all versions of tera-guide-core.

**Comment by erika2145154** [comment]
> 
> 
> Your error says a folder "tera-guide-core-master" it is not the correct path to load. Just remove all versions of tera-guide-core.

[21:13:46.403] [mods] ERROR: Module "tera-guide" could not be preloaded!
[21:13:46.404] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[21:13:46.405] Error: Cannot find module 'C:\Users\erika\AppData\Local\Programs\TeraToolbox\mods\tera-guide'
Require stack:
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\proxy.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\index-gui.js
- C:\Users\erika\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7012:16)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Mod.loadCache (C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod.js:440:35)
    at ModManager.load (C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:128:22)
    at C:\Users\erika\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:102:22
    at Map.forEach (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\mod.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\mod-manager.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\proxy.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\loader-gui.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\bin\\index-gui.js',
    'C:\\Users\\erika\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
    undefined
  ]
}

**Comment by shindmitry** [comment]
Also, check if you have automatic updates enabled in the toolbox.

**Comment by shindmitry** [comment]
After this try to full restart the toolbox, or restart your computer.

**Comment by erika2145154** [comment]
> 
> 
> After this try to full restart the toolbox, or restart your computer.

Restarted toolbox and disabled updates, I got it to work. Thank you for your time 👍
