### ISSUE TITLE
Can't load core

### ISSUE THREAD

**Issue by michaelcarno** [hsdn/tera-guide#46]
Don't know where to post this ussues;
Module named as **tera-guide-core** and placed in **mods**;
Used on pinki proxy;
Worked fine until yesterday;

```
07:23:47 Error: [tera-guide] Warning!
Depended module "tera-guide-core" needed for TERA-Guide is not installed!
Please download and install: https://github.com/hsdn/tera-guide-core

07:23:47 Error: [tera-proxy-game] TypeError: Cannot read property 'GlobalMod' of undefined
    at CompatWrapper.init (G:\pinki\proxy\node_modules\tera-proxy-game\connection\dispatch\wrapper-compat.js:110:22)
    at G:\pinki\proxy\mods\tera-guide-core\index.js:56:15
    at Array.forEach (<anonymous>)
    at TeraGuideCore.load (G:\pinki\proxy\mods\tera-guide-core\index.js:54:21)
    at new module.exports.NetworkMod (G:\pinki\proxy\mods\tera-guide\index.js:5:34)
    at CompatWrapper.init (G:\pinki\proxy\node_modules\tera-proxy-game\connection\dispatch\wrapper-compat.js:112:62)
    at Dispatch.load (G:\pinki\proxy\node_modules\tera-proxy-game\connection\dispatch\index.js:163:8)
    at Dispatch.loadAll (G:\pinki\proxy\node_modules\tera-proxy-game\connection\dispatch\index.js:137:65)
    at Dispatch.<anonymous> (G:\pinki\proxy\bin\cli\index.js:103:14)
    at Object.onceWrapper (events.js:420:28)
```

Thanks for module and updates!

**Comment by jk-q** [comment]
Hi,
I recommend full reinstalling (and updating) the proxy and all guide modules. 
If this does not help, please contact with the support community of pinki proxy.

Also we have not declared support for pinki proxy in our module, at the moment only TeraToolbox is full supported, therefore there may be problems or errors if you use other proxy.

**Comment by jk-q** [comment]
There was a compatibility problem.
Fixed in the latest update of tera-guide-core.
