### ISSUE TITLE
can't install the module

### ISSUE THREAD

**Issue by sheldox** [hsdn/tera-guide#70]
Hey, how should i fix this, i get the error only with tera guide, and cant use it. I tried delete tera guide master from mods folder and downloaded the new one from here, but always got this error and the module not working.

```
[22:44:35.375]` [update] Initialized dependency "tera-guide-core" for module "tera-guide"
[22:44:36.631] [update] ERROR: Unable to auto-update module library:
[22:44:36.632] Error: Unable to download update manifest for module "library":
ERROR: https://raw.githubusercontent.com/Kasea/library/master/manifest.json
Can't download file from update server (404 - Not Found)! Possible causes:
   + Incorrect manifest specified by developer
   + Server is not available anymore
   + Access denied
   + Internal server error
    at autoUpdateModule (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\update.js:130:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async autoUpdate (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\update.js:246:42)
    at async StartProxy (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js:122:25)
[22:44:36.633] [update] Please go to https://github.com/Kaseaa/library/issues and follow the given instructions or ask for help.
[22:44:36.634] [update] Alternatively, ask here: https://discord.gg/659YbNY
[22:44:37.405] [update] Installing module tera-guide-core
[22:44:49.066] [update] Auto-update complete!
[22:44:49.067] [update] ERROR: Module library could not be updated and might be broken!
[22:44:49.068] [update] ERROR: Module library could not be updated and might be broken!

[23:04:22.854] [mods] Applied module "Guide Core" (tera-guide-core) to server connection
[23:04:22.858] [Library] Failed to load module entity. Will close.
[23:04:22.858] [mods] ERROR: Module "library" could not be applied to server connection!
[23:04:22.858] [mods] ERROR: Please contact the module's author: https://github.com/Kaseaa/library/issues
[23:04:22.858] Error: [dispatch] [library] hook: Error: obsolete definition (S_EACH_SKILL_RESULT.14)
    at Dispatch.createHook (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at NetworkModInterface.hook (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\mod.js:280:36)
    at new entity (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\library\class\entity.js:139:70)
    at Library.loadAllModules (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\library\index.js:25:24)
    at new Library (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\library\index.js:35:57)
    at new Require (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\library\index.js:44:9)
    at Mod.loadNetworkInstance (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\mod.js:595:31)
    at Object.get (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\mod.js:207:38)
    at new Commands (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\commands.js:15:34)
[23:04:22.858] [tera-guide] ERROR: Warning!
Depended module "tera-guide-core" needed for TERA-Guide is not installed!
Please download and install: https://github.com/hsdn/tera-guide-core

[23:04:22.858] [mods] ERROR: Module "Guide" (tera-guide) could not be applied to server connection!
[23:04:22.859] [mods] ERROR: Please contact the module's author: https://github.com/hsdn/tera-guide/issues
[23:04:22.859] TypeError: Cannot destructure property 'player' of 'mod.require.library' as it is null.
    at new Commands (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\lib\core\commands.js:15:11)
    at C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\index.js:49:56
    at Array.forEach (<anonymous>)
    at new TeraGuideCore (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\index.js:49:14)
    at Loader.load (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\tera-guide-core\index.js:69:10)
    at new module.exports.NetworkMod (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\mods\tera-guide-master\index.js:5:34)
    at Mod.loadNetworkInstance (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:252:20)
    at C:\Users\fnorb\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
```

**Comment by jk-q** [comment]
Hi. 
It is library issue. 
You need delete **library** module from your mods folder and restart TeraToolbox.
The correct version of the library will be installed automatically.

**Comment by sheldox** [comment]
Thanks.
