### ISSUE TITLE
Module "tera-guide" could not be preloaded! (:(

### ISSUE THREAD

**Issue by hambonss** [hsdn/tera-guide#71]
[mods] ERROR: Module "tera-guide" could not be preloaded!
 [mods] ERROR: Please contact the module's author: https://github.com/Kaseaa/tera-guide/issues
 Error: Cannot find module 'E:\Games\tera\TeraToolbox\mods\tera-guide'
Require stack:
- E:\Games\tera\TeraToolbox\bin\mod.js
- E:\Games\tera\TeraToolbox\bin\mod-manager.js
- E:\Games\tera\TeraToolbox\bin\proxy.js
- E:\Games\tera\TeraToolbox\bin\loader-gui.js
- E:\Games\tera\TeraToolbox\bin\index-gui.js
- E:\Games\tera\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Mod.loadCache (E:\Games\tera\TeraToolbox\bin\mod.js:440:35)
    at ModManager.load (E:\Games\tera\TeraToolbox\bin\mod-manager.js:128:22)
    at E:\Games\tera\TeraToolbox\bin\mod-manager.js:102:22
    at Map.forEach (<anonymous>) {
  code: 'MODULE_NOT_FOUND',

**Comment by jk-q** [comment]
You need to completely remove all tera-guide modules and then install our module from the link https://github.com/hsdn/tera-guide/archive/refs/heads/master.zip
